@startuml
title Aktivitas: Proses Mengikuti Pembelajaran

skinparam backgroundColor #FEFEFE
skinparam ActivityBorderColor #9E9E9E
skinparam ArrowColor #555555

|Customer|
start
:Buka halaman
belajar kelas; <<#FFF9C4>>
:Lihat daftar
materi; <<#FFF9C4>>
:Pilih materi; <<#FFF9C4>>

if (Tipe materi?) then (Video)
    :Tonton video
pembelajaran; <<#FFF9C4>>
else (Lainnya)
    if (PDF?) then (Ya)
        :Baca dokumen PDF; <<#FFF9C4>>
    else (Kuis)
        :Mulai kerjakan
Kuis; <<#FFF9C4>>
        :Jawab soal-soal
kuis; <<#FFF9C4>>
        :Kirim jawaban; <<#FFF9C4>>

        |Sistem|
        :Hitung nilai
ujian; <<#FFFFFF>>
        :Cek kelulusan
(nilai >= 80); <<#FFFFFF>>

        |Customer|
        if (Lulus?) then (Ya)
            :Tampilkan pesan
berhasil; <<#FFF9C4>>
            :Tandai kuis
selesai; <<#FFF9C4>>
        else (Tidak)
            :Tampilkan pesan
gagal, minta
ulangi; <<#FFF9C4>>
            detach
        endif
    endif
endif

|Sistem|
:Perbarui persentase
progres belajar; <<#FFFFFF>>
:Cek apakah semua
materi wajib
selesai; <<#FFFFFF>>

if (Semua selesai?) then (Ya)
    :Buka akses
klaim sertifikat; <<#FFFFFF>>
endif

stop
@enduml


