@startuml
title Aktivitas: Pendaftaran dan Login Pengguna

skinparam backgroundColor #FEFEFE
skinparam ActivityBorderColor #9E9E9E
skinparam ArrowColor #555555

|Guest|
start
:Buka platform
e-learning; <<#E8F5E9>>

if (Sudah punya akun?) then (Ya)
    :Buka halaman
Login; <<#E8F5E9>>
    :Masukkan Email
dan Kata Sandi; <<#E8F5E9>>
    :Kirim data login; <<#E8F5E9>>
else (Belum)
    :Buka halaman
Daftar; <<#E8F5E9>>
    :Masukkan Nama,
Email, dan
Kata Sandi; <<#E8F5E9>>
    :Kirim data
pendaftaran; <<#E8F5E9>>
    :Akun berhasil
dibuat
(Otomatis Login); <<#E8F5E9>>
endif

|Sistem|
:Validasi data
kredensial; <<#FFFFFF>>

if (Valid?) then (Ya)
    :Cek peran
pengguna; <<#FFFFFF>>
    if (Admin?) then (Ya)
        :Arahkan ke
Dashboard Admin; <<#FFFFFF>>
    else (Bukan Admin)
        if (Dosen?) then (Ya)
            :Arahkan ke
Dashboard Dosen; <<#FFFFFF>>
        else (Customer)
            :Arahkan ke
Dashboard
Customer; <<#FFFFFF>>
        endif
    endif
else (Tidak)
    :Tampilkan pesan
kesalahan; <<#FFFFFF>>
    :Kembali ke
form login; <<#FFFFFF>>
    detach
endif

stop
@enduml


